import ManagerTemplate from "@/components/managerTemplate"
import MenuList from "../../menuList"

export const metadata = {
    title: 'Profil | Ordering System',
    description: 'Generated by create next app',
}

type PropsLayout = {
    children: React.ReactNode
}

const RootLayout = ({ children }: PropsLayout) => {
    return (
        <ManagerTemplate title="Profil" id="profil" menuList={MenuList}>
            {children}
        </ManagerTemplate>
    )
}

export default RootLayout